
# services:
#   backend:
#     build: ./referral-wallet-system
#     image: local-backend:latest
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_PROFILES_ACTIVE=prod
#       - JWT_SECRET=SuperSecretKey
#     healthcheck:
#       test: ["CMD-SHELL", "curl -u admin:password -f http://localhost:8080/actuator/health || exit 1"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
  
#   frontend:
#     build: ./my-app
#     image: local-frontend:latest
#     ports:
#       - "3000:3000"
#     environment:
#       - NEXT_PUBLIC_BACKEND_URL=https://api.gramflix.in
#     depends_on:
#       - backend



# services:
#   backend:
#     build: ./referral-wallet-system
#     image: local-backend:latest
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_PROFILES_ACTIVE=prod
#       - JWT_SECRET=SuperSecretKey

#   frontend:
#     build: ./my-app
#     image: local-frontend:latest
#     ports:
#       - "3000:3000"
#     environment:
#       - NEXT_PUBLIC_BACKEND_URL=https://api.gramflix.in
#     depends_on:
#       - backend


services:
  backend:
    build: ./referral-wallet-system
    image: local-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=SuperSecretKey

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile.prod
    image: local-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

