// import { Geist, Geist_Mono } from "next/font/google";
// import './globals.css';

// import { Inter } from "next/font/google"

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${inter.variable}`}>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

"use client";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import SidebarNav from "@/components/SidebarNav";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  // ⚡ Theme + Login state can be controlled globally
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  return (
    <html lang="en" className={`${inter.variable} ${isDarkMode ? "dark" : ""}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar stays on top for every route */}
        <Navbar
          isDarkMode={isDarkMode}
          onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
          isLoggedIn={isLoggedIn}
        />

        {/* Sidebar (desktop only) */}
        <SidebarNav />

        {/* Page Content */}
        <main className="md:ml-64 pt-5 pb-20 md:pb-4">
          {children}
        </main>
      </body>
    </html>
  );
}

