# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://mlmproject1010:MJjxAdNovHDTaHgZ@cluster0.pcglc8t.mongodb.net/referralwallet?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=referralwallet

# JWT
app.jwt.secret=SuperSecretKey
app.jwt.expirationMs=3600000
jwt.expiration=604800000

# Email (Gmail) - use env vars or app-specific password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=techmagicop@gmail.com
spring.mail.password=Sameer@1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# ==== Twilio WhatsApp (Sandbox) ====
twilio.accountSid=${TWILIO_ACCOUNT_SID:ACd0646e30701267f2159aab3bf35fb4a1}
twilio.authToken=${TWILIO_AUTH_TOKEN:ff7417f9eeb8ce5162da168204fcd0c0}
# Must include the whatsapp: prefix and the sandbox number
twilio.whatsapp-from-number=whatsapp:+14155238886
# ==== OTP behavior ====
# When true, API will include the OTP in the response (dev-only)
otp.dev-echo=true
# default channel if not provided (whatsapp or email)
otp.default-channel=whatsapp
