# ==== MongoDB Atlas connection ====

# --------------- LOcal Hosting------------------#

# spring.data.mongodb.uri=mongodb+srv://mlmproject1010:MJjxAdNovHDTaHgZ@cluster0.pcglc8t.mongodb.net/referralwallet?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.database=referralwallet
# app.frontend.url=http://localhost:3000


# --------------- Production Hosting------------------#


spring.data.mongodb.uri=mongodb+srv://gramflix:wix0Qqco94FCnSEp@gramflix.yhu15ti.mongodb.net/gramflix?retryWrites=true&w=majority&appName=Gramflix
spring.data.mongodb.database=gramflix
app.frontend.url=https://gramflix.in

# ==== JWT Configuration ====
app.jwt.secret=SuperSecretKey
app.jwt.expirationMs=3600000


jwt.expiration=604800000

# ==== Gmail SMTP for sending all emails to admin ====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projecttesting897@gmail.com   
spring.mail.password=pjzzgomhbugueefn            
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=projecttesting897@gmail.com        # all emails go to admin

# ==== Logging ====
logging.level.root=ERROR
logging.level.org.springframework.boot.web=INFO
logging.level.org.springframework.boot.context=INFO
spring.main.banner-mode=off


# ==== MSG91 Configuration ====
# msg91.authKey=466454AmXVLu00Y68af75cbP1
# msg91.smsTemplateId=68b83f977772651a661d88e2
# msg91.whatsappTemplateId=68b83f977772651a661d88e2

# ==== OTP behavior ====
otp.dev-echo=true
otp.default-channel=sms

# ==== Referral Signup URL ====
app.referral.signup-url=https://gramflix.in/signup?referralId=

# ==== Mediastack API Configuration ====
mediastack.api.key=b7f231b520c3be77a65d7e8bf864a1e4
mediastack.api.base-url=https://api.mediastack.com/v1

# ==== Cache Configuration ====
spring.cache.type=caffeine
spring.cache.cache-names=newsCache,newsCategoryCache,latestNewsCache

# ==== News Cleanup Configuration ====
news.cleanup.enabled=true
news.cleanup.retention-days=2
news.cleanup.schedule-hours=12
