name: Deploy Backend

on:
  push:
    branches: [ "master" ]
    paths:
      - "referral-wallet-system/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run remote deploy script
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} "
            cd gramflix/referral-wallet-system &&
            git pull &&
            mvn clean package -DskipTests &&
            pm2 delete gramflix-backend || true &&
            pm2 start \"java -jar target/referral-wallet-system-0.0.1-SNAPSHOT.jar\" --name gramflix-backend
          "
